esphome:
  name: huawei_r4850
  friendly_name: Huawei R4850

external_components:
  - source: github://mb-software/esphome-huawei-r4850

esp32:
  board: esp32dev

# Enable logging
logger:
  level: DEBUG
  logs:
    canbus: INFO

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:

canbus:
  - platform: esp32_can
    id: can
    tx_pin: GPIO14
    rx_pin: GPIO27
    use_extended_id: true
    can_id: 0
    bit_rate: 125kbps


huawei_r4850:
  canbus_id: can
  update_interval: 5s

sensor:
  - platform: huawei_r4850
    output_voltage:
      name: Output voltage
    output_current:
      name: Output current
    output_power:
      name: Output power
    input_voltage:
      name: Input voltage
    input_current:
      name: Input current
    input_power:
      name: Input power
    input_frequency:
      name: Input frequency
    efficiency:
      name: Efficiency
    input_temp:
      name: Input temperature
    output_temp:
      name: Output temperature
    

number:
  - platform: huawei_r4850
    output_voltage:
      name: Set output voltage
    max_output_current:
      name: Max output current

button:
  - platform: huawei_r4850
    set_offline_values:
      name: Set offline values
      